:- module(stage8_external_backends,
          [ export_proof/3,
            export_proof_text/3,
            lean_exporter/3,
            coq_exporter/3,
            smtlib_exporter/3,
            tptp_exporter/3
          ]).

:- use_module('./stage5_proof_search', [universal_prove/3]).
:- use_module(library(filesex)).

export_proof(Theorem, Backend, File) :-
    resolve_output_file(Theorem, Backend, File, OutputFile),
    export_proof_text(Theorem, Backend, Text),
    ensure_parent_directory(OutputFile),
    setup_call_cleanup(
        open(OutputFile, write, Stream),
        write(Stream, Text),
        close(Stream)
    ).

export_proof_text(Theorem, Backend, Text) :-
    must_be_backend(Backend),
    build_export_context(Theorem, Context),
    backend_exporter(Backend, Exporter),
    call(Exporter, Theorem, Context, Text).

lean_exporter(Theorem, context(Result, Formula), Text) :-
    theorem_formula(Theorem, Formula, FormulaText),
    format(atom(Text),
           'theorem ~w (n : Nat) : recursive_sum n = ~w := by~n  -- generated by Gaussian-Theorem-Prover~n  -- proof status: ~w~n  admit~n',
           [Theorem, FormulaText, Result]).

coq_exporter(Theorem, context(Result, Formula), Text) :-
    theorem_formula(Theorem, Formula, FormulaText),
    format(atom(Text),
           'Theorem ~w : forall n:nat, recursive_sum n = ~w.~nProof.~n  (* generated by Gaussian-Theorem-Prover *)~n  (* proof status: ~w *)~nAdmitted.~n',
           [Theorem, FormulaText, Result]).

smtlib_exporter(Theorem, context(Result, Formula), Text) :-
    theorem_formula(Theorem, Formula, FormulaText),
    format(atom(Text),
           '; generated by Gaussian-Theorem-Prover~n; theorem ~w~n; proof status ~w~n(set-logic AUFNIA)~n(declare-fun n () Int)~n(assert (>= n 0))~n(assert (not (= (recursive_sum n) ~w)))~n(check-sat)~n',
           [Theorem, Result, FormulaText]).

tptp_exporter(Theorem, context(Result, Formula), Text) :-
    theorem_formula(Theorem, Formula, FormulaText),
    format(atom(Text),
           '%% generated by Gaussian-Theorem-Prover~n%% proof status ~w~nfof(~w, conjecture, ! [N] : ( recursive_sum(N) = ~w )).~n',
           [Result, Theorem, FormulaText]).

resolve_output_file(Theorem, Backend, File, OutputFile) :-
    (   var(File)
    ->  backend_extension(Backend, Extension),
        format(atom(OutputFile), 'exports/~w.~w', [Theorem, Extension]),
        File = OutputFile
    ;   OutputFile = File
    ).

must_be_backend(Backend) :-
    (   backend_extension(Backend, _)
    ->  true
    ;   throw(error(domain_error(export_backend, Backend), stage8_external_backends/3))
    ).

backend_exporter(lean, lean_exporter).
backend_exporter(coq, coq_exporter).
backend_exporter(smtlib, smtlib_exporter).
backend_exporter(tptp, tptp_exporter).

backend_extension(lean, 'lean').
backend_extension(coq, 'v').
backend_extension(smtlib, 'smt2').
backend_extension(tptp, 'p').

build_export_context(Theorem, context(Result, Formula)) :-
    universal_prove(Theorem, Result, Evidence),
    discovered_formula(Evidence, Formula),
    !.
build_export_context(_Theorem, context(failed, unknown)).

discovered_formula(evidence(strategies(_), lemmas(Lemmas), _, _, _), Formula) :-
    member(lemma(discovered_formula(_Predicate, Formula)), Lemmas),
    !.
discovered_formula(_Evidence, unknown).

theorem_formula(sum_formula, unknown, '(n*(n+1))/2') :-
    !.
theorem_formula(_Theorem, unknown, 'goal_formula').
theorem_formula(_Theorem, Formula, FormulaText) :-
    term_string(Formula, FormulaText).

ensure_parent_directory(FilePath) :-
    file_directory_name(FilePath, Directory),
    (   Directory == '.'
    ->  true
    ;   make_directory_path(Directory)
    ).
