:- module(stage8_external_backends,
          [ export_proof/2,
            export_proof/3,
            export_proof_text/3,
            lean_exporter/3,
            coq_exporter/3,
            smtlib_exporter/3,
            tptp_exporter/3
          ]).

:- use_module('./stage5_proof_search', [universal_prove/3]).
:- use_module(library(filesex)).

export_proof(Theorem, Backend, File) :-
    must_be_backend(Backend),
    (   var(File)
    ->  default_output_file(Theorem, Backend, OutputFile),
        export_proof_to_file(Theorem, Backend, OutputFile),
        File = OutputFile
    ;   export_proof_to_file(Theorem, Backend, File)
    ).

export_proof(Theorem, Backend) :-
    must_be_backend(Backend),
    default_output_file(Theorem, Backend, OutputFile),
    export_proof_to_file(Theorem, Backend, OutputFile).

export_proof_to_file(Theorem, Backend, OutputFile) :-
    export_proof_text(Theorem, Backend, Text),
    ensure_parent_directory(OutputFile),
    setup_call_cleanup(
        open(OutputFile, write, Stream),
        write(Stream, Text),
        close(Stream)
    ).

export_proof_text(Theorem, Backend, Text) :-
    must_be_backend(Backend),
    build_export_context(Theorem, Context),
    backend_exporter(Backend, Exporter),
    call(Exporter, Theorem, Context, Text).

lean_exporter(Theorem, context(Result, Formula), Text) :-
    theorem_formula(Theorem, Formula, FormulaText),
    theorem_profile(Theorem, profile(vars(lean(LeanVar), _, _, _), lhs(lean(LeanLhs), _, _, _), _)),
    format(atom(Text),
           'theorem ~w (~w) : ~w = ~w := by~n  -- generated by Gaussian-Theorem-Prover~n  -- proof status: ~w~n  admit~n',
           [Theorem, LeanVar, LeanLhs, FormulaText, Result]).

coq_exporter(Theorem, context(Result, Formula), Text) :-
    theorem_formula(Theorem, Formula, FormulaText),
    theorem_profile(Theorem, profile(vars(_, coq(CoqVar), _, _), lhs(_, coq(CoqLhs), _, _), _)),
    format(atom(Text),
           'Theorem ~w : forall ~w, ~w = ~w.~nProof.~n  (* generated by Gaussian-Theorem-Prover *)~n  (* proof status: ~w *)~nAdmitted.~n',
           [Theorem, CoqVar, CoqLhs, FormulaText, Result]).

smtlib_exporter(Theorem, context(Result, Formula), Text) :-
    theorem_formula(Theorem, Formula, FormulaText),
    theorem_profile(Theorem, profile(vars(_, _, smt(SmtVar), _), lhs(_, _, smt(SmtLhs), _), _)),
    format(atom(Text),
           '; generated by Gaussian-Theorem-Prover~n; theorem ~w~n; proof status ~w~n(set-logic AUFNIA)~n(declare-fun ~w () Int)~n(assert (>= ~w 0))~n(assert (not (= ~w ~w)))~n(check-sat)~n',
           [Theorem, Result, SmtVar, SmtVar, SmtLhs, FormulaText]).

tptp_exporter(Theorem, context(Result, Formula), Text) :-
    theorem_formula(Theorem, Formula, FormulaText),
    theorem_profile(Theorem, profile(vars(_, _, _, tptp(TptpVar)), lhs(_, _, _, tptp(TptpLhs)), _)),
    format(atom(Text),
           '%% generated by Gaussian-Theorem-Prover~n%% proof status ~w~nfof(~w, conjecture, ! [~w] : ( ~w = ~w )).~n',
           [Result, Theorem, TptpVar, TptpLhs, FormulaText]).

default_output_file(Theorem, Backend, OutputFile) :-
    backend_extension(Backend, Extension),
    format(atom(OutputFile), 'exports/~w.~w', [Theorem, Extension]).

must_be_backend(Backend) :-
    (   backend_extension(Backend, _)
    ->  true
    ;   throw(error(domain_error(export_backend, Backend), must_be_backend/1))
    ).

backend_exporter(lean, lean_exporter).
backend_exporter(coq, coq_exporter).
backend_exporter(smtlib, smtlib_exporter).
backend_exporter(tptp, tptp_exporter).

backend_extension(lean, 'lean').
backend_extension(coq, 'v').
backend_extension(smtlib, 'smt2').
backend_extension(tptp, 'p').

build_export_context(Theorem, context(Result, Formula)) :-
    (   universal_prove(Theorem, Result, Evidence)
    ->  discovered_formula(Evidence, Formula)
    ;   Result = failed,
        Formula = unknown
    ).

discovered_formula(Evidence, Formula) :-
    (   Evidence = evidence(strategies(_), lemmas(Lemmas), _, _, _),
        once(member(lemma(discovered_formula(_, FoundFormula)), Lemmas))
    ->  Formula = FoundFormula
    ;   Formula = unknown
    ).

theorem_formula(Theorem, Formula, FormulaText) :-
    (   Formula == unknown
    ->  theorem_profile(Theorem, profile(_, _, default_formula(FormulaText)))
    ;   term_string(Formula, FormulaText)
    ).

theorem_profile(Theorem, Profile) :-
    theorem_profile_entry(Theorem, Profile),
    !.
theorem_profile(Theorem, _Profile) :-
    format(atom(Message), 'No export profile is defined for theorem ~w.', [Theorem]),
    throw(error(existence_error(export_profile, Theorem),
                context(stage8_external_backends:theorem_profile/2, Message))).

theorem_profile_entry(sum_formula,
                     profile(
                         vars(lean('n : Nat'), coq('n:nat'), smt('n'), tptp('N')),
                         lhs(lean('recursive_sum n'), coq('recursive_sum n'), smt('recursive_sum n'), tptp('recursive_sum(N)')),
                         default_formula('n*(n+1)/2')
                     )).

ensure_parent_directory(FilePath) :-
    file_directory_name(FilePath, Directory),
    (   Directory == '.'
    ->  true
    ;   make_directory_path(Directory)
    ).
