:- module(stage8_external_backends,
          [ export_proof/2,
            export_proof/3,
            export_proof_text/3,
            lean_exporter/3,
            coq_exporter/3,
            smtlib_exporter/3,
            tptp_exporter/3
          ]).

:- use_module('./stage5_proof_search', [universal_prove/3]).
:- use_module(library(filesex)).

export_proof(Theorem, Backend, File) :-
    must_be_backend(Backend),
    (   var(File)
    ->  default_output_file(Theorem, Backend, OutputFile),
        export_proof_to_file(Theorem, Backend, OutputFile),
        File = OutputFile
    ;   export_proof_to_file(Theorem, Backend, File)
    ).

export_proof(Theorem, Backend) :-
    must_be_backend(Backend),
    default_output_file(Theorem, Backend, OutputFile),
    export_proof_to_file(Theorem, Backend, OutputFile).

export_proof_to_file(Theorem, Backend, OutputFile) :-
    export_proof_text(Theorem, Backend, Text),
    ensure_parent_directory(OutputFile),
    setup_call_cleanup(
        open(OutputFile, write, Stream),
        write(Stream, Text),
        close(Stream)
    ).

export_proof_text(Theorem, Backend, Text) :-
    must_be_backend(Backend),
    build_export_context(Theorem, Context),
    backend_exporter(Backend, Exporter),
    call(Exporter, Theorem, Context, Text).

lean_exporter(Theorem, context(Result, Formula), Text) :-
    theorem_formula(Theorem, Formula, FormulaText),
    theorem_subject(Theorem, subject(LeanVar, _CoqVar, _SmtVar, _TptpVar, LeanLhs, _CoqLhs, _SmtLhs, _TptpLhs)),
    format(atom(Text),
           'theorem ~w (~w) : ~w = ~w := by~n  -- generated by Gaussian-Theorem-Prover~n  -- proof status: ~w~n  admit~n',
           [Theorem, LeanVar, LeanLhs, FormulaText, Result]).

coq_exporter(Theorem, context(Result, Formula), Text) :-
    theorem_formula(Theorem, Formula, FormulaText),
    theorem_subject(Theorem, subject(_LeanVar, CoqVar, _SmtVar, _TptpVar, _LeanLhs, CoqLhs, _SmtLhs, _TptpLhs)),
    format(atom(Text),
           'Theorem ~w : forall ~w, ~w = ~w.~nProof.~n  (* generated by Gaussian-Theorem-Prover *)~n  (* proof status: ~w *)~nAdmitted.~n',
           [Theorem, CoqVar, CoqLhs, FormulaText, Result]).

smtlib_exporter(Theorem, context(Result, Formula), Text) :-
    theorem_formula(Theorem, Formula, FormulaText),
    theorem_subject(Theorem, subject(_LeanVar, _CoqVar, SmtVar, _TptpVar, _LeanLhs, _CoqLhs, SmtLhs, _TptpLhs)),
    format(atom(Text),
           '; generated by Gaussian-Theorem-Prover~n; theorem ~w~n; proof status ~w~n(set-logic AUFNIA)~n(declare-fun ~w () Int)~n(assert (>= ~w 0))~n(assert (not (= (~w) ~w)))~n(check-sat)~n',
           [Theorem, Result, SmtVar, SmtVar, SmtLhs, FormulaText]).

tptp_exporter(Theorem, context(Result, Formula), Text) :-
    theorem_formula(Theorem, Formula, FormulaText),
    theorem_subject(Theorem, subject(_LeanVar, _CoqVar, _SmtVar, TptpVar, _LeanLhs, _CoqLhs, _SmtLhs, TptpLhs)),
    format(atom(Text),
           '%% generated by Gaussian-Theorem-Prover~n%% proof status ~w~nfof(~w, conjecture, ! [~w] : ( ~w = ~w )).~n',
           [Result, Theorem, TptpVar, TptpLhs, FormulaText]).

default_output_file(Theorem, Backend, OutputFile) :-
    backend_extension(Backend, Extension),
    format(atom(OutputFile), 'exports/~w.~w', [Theorem, Extension]).

must_be_backend(Backend) :-
    (   backend_extension(Backend, _)
    ->  true
    ;   throw(error(domain_error(export_backend, Backend), must_be_backend/1))
    ).

backend_exporter(lean, lean_exporter).
backend_exporter(coq, coq_exporter).
backend_exporter(smtlib, smtlib_exporter).
backend_exporter(tptp, tptp_exporter).

backend_extension(lean, 'lean').
backend_extension(coq, 'v').
backend_extension(smtlib, 'smt2').
backend_extension(tptp, 'p').

build_export_context(Theorem, context(Result, Formula)) :-
    (   universal_prove(Theorem, Result, Evidence)
    ->  discovered_formula(Evidence, Formula)
    ;   Result = failed,
        Formula = unknown
    ).

discovered_formula(Evidence, Formula) :-
    (   Evidence = evidence(strategies(_), lemmas(Lemmas), _, _, _),
        once(member(lemma(discovered_formula(_Predicate, FoundFormula)), Lemmas))
    ->  Formula = FoundFormula
    ;   Formula = unknown
    ).

theorem_formula(Theorem, Formula, FormulaText) :-
    (   Formula == unknown
    ->  theorem_default_formula(Theorem, FormulaText)
    ;   term_string(Formula, FormulaText)
    ).

theorem_default_formula(sum_formula, 'n*(n+1)/2').

theorem_subject(sum_formula,
                subject('n : Nat', 'n:nat', 'n', 'N',
                        'recursive_sum n', 'recursive_sum n', 'recursive_sum n', 'recursive_sum(N)')).
theorem_subject(Theorem, _Subject) :-
    throw(error(existence_error(export_signature, Theorem), theorem_subject/2)).

theorem_default_formula(Theorem, _FormulaText) :-
    throw(error(existence_error(export_formula, Theorem), theorem_default_formula/2)).

ensure_parent_directory(FilePath) :-
    file_directory_name(FilePath, Directory),
    (   Directory == '.'
    ->  true
    ;   make_directory_path(Directory)
    ).
